server:
  port: 8401

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  lims :
    url : http://127.0.0.1:8070

spring:
  redis:
    host: 1.14.62.114
    port: 6379
    password: rystars
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms